os:
  - linux

language: php

php:
  - '7.4'
  
before_script:
  - composer self-update
  - composer install --no-interaction
  - pear install pear/PHP_CodeSniffer
  - phpenv rehash
  - nvm install 12.16
  - npm install npm@latest -g
  - npm install -g jshint
  - npm install
  - cp .env.example .env
  - php artisan key:generate
  
script:
  - vendor/bin/phpunit --coverage-text
  - phpcs --standard=PSR2 --ignore=app/Http/Controllers/Auth,app/Http/Controllers/Controller.php app/Http/Controllers
  - npm run production
  - jshint resources/js/*
